on: [push]

jobs:
  build_docker_postgreqsql:
    runs-on: ubuntu-latest
    name: Building docker-postgresql
    steps:
    - name: 01-list
      run: ls -l
    - name: 02-build
      run: make build-12.2
