on: [push]

jobs:
  build_docker_postgreqsql:
    runs-on: ubuntu-latest
    name: Building docker-postgresql
    steps:
    - name: 01-master
      id: master
      uses: actions/checkout@master
#      with:
#        args: build-12.2
    - name: 01-list
      run: ls -l
    - name: 02-build
      run: make ${{steps.master.args }}
